# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('popnews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='articlesave',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popnews.Article'),
        ),
        migrations.AddField(
            model_name='articlesave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(through='popnews.ArticleSave', to=settings.AUTH_USER_MODEL),
        ),
    ]
