# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popnews', '0002_auto_20170624_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
