# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popnews', '0003_article_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=140, null=True),
        ),
    ]
