# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popnews', '0004_auto_20170625_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bias',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
